application: geolocation408
version: 1
runtime: php
api_version: 1
handlers:

- url: /web/viewer.html
  script: /web/viewer.html

- url: /projectplan.php
  script: projectplan.php

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: index.php

